export const mockCommunities = [
  {
    id: '1',
    name: 'IM 22 Batch',
    description: 'Information Management 2022 Batch Community',
    memberCount: 45,
    image: 'https://images.pexels.com/photos/3184291/pexels-photo-3184291.jpeg?auto=compress&cs=tinysrgb&w=400',
    resources: [
      {
        id: '1',
        title: 'Database Management Notes',
        description: 'Comprehensive notes on SQL and database design',
        tags: ['Database', 'SQL', 'Notes'],
        type: 'PDF',
        uploadedBy: 'John Doe',
        uploadedAt: '2024-01-15',
        downloads: 45,
        fileSize: '2.3 MB',
      },
      {
        id: '2',
        title: 'Web Development Tutorial',
        description: 'HTML, CSS, and JavaScript basics',
        tags: ['Web Dev', 'HTML', 'CSS', 'JavaScript'],
        type: 'PDF',
        uploadedBy: 'Jane Smith',
        uploadedAt: '2024-01-14',
        downloads: 32,
        fileSize: '1.8 MB',
      },
    ],
  },
  {
    id: '2',
    name: 'CS 21 Batch',
    description: 'Computer Science 2021 Batch Community',
    memberCount: 38,
    image: 'https://images.pexels.com/photos/574071/pexels-photo-574071.jpeg?auto=compress&cs=tinysrgb&w=400',
    resources: [
      {
        id: '3',
        title: 'Data Structures & Algorithms',
        description: 'Complete guide to DSA concepts',
        tags: ['DSA', 'Algorithms', 'Programming'],
        type: 'PDF',
        uploadedBy: 'Mike Johnson',
        uploadedAt: '2024-01-13',
        downloads: 78,
        fileSize: '4.1 MB',
      },
      {
        id: '4',
        title: 'Machine Learning Projects',
        description: 'Collection of ML project examples',
        tags: ['ML', 'AI', 'Python', 'Projects'],
        type: 'ZIP',
        uploadedBy: 'Sarah Wilson',
        uploadedAt: '2024-01-12',
        downloads: 56,
        fileSize: '15.2 MB',
      },
    ],
  },
  {
    id: '3',
    name: 'Mathematics Society',
    description: 'Mathematics enthusiasts and students',
    memberCount: 67,
    image: 'https://images.pexels.com/photos/6238297/pexels-photo-6238297.jpeg?auto=compress&cs=tinysrgb&w=400',
    resources: [
      {
        id: '5',
        title: 'Calculus Problem Sets',
        description: 'Practice problems with solutions',
        tags: ['Calculus', 'Math', 'Practice'],
        type: 'PDF',
        uploadedBy: 'Dr. Brown',
        uploadedAt: '2024-01-11',
        downloads: 89,
        fileSize: '3.7 MB',
      },
    ],
  },
  {
    id: '4',
    name: 'Physics Club',
    description: 'Physics students and researchers',
    memberCount: 42,
    image: 'https://images.pexels.com/photos/346885/pexels-photo-346885.jpeg?auto=compress&cs=tinysrgb&w=400',
    resources: [
      {
        id: '6',
        title: 'Quantum Mechanics Notes',
        description: 'Advanced quantum mechanics concepts',
        tags: ['Physics', 'Quantum', 'Advanced'],
        type: 'PDF',
        uploadedBy: 'Prof. Davis',
        uploadedAt: '2024-01-10',
        downloads: 34,
        fileSize: '5.2 MB',
      },
    ],
  },
];

export const mockResources = [
  {
    id: '1',
    title: 'Advanced Mathematics Notes',
    category: 'Mathematics',
    type: 'PDF',
    uploadedBy: 'John Doe',
    uploadedAt: '2024-01-15',
    url: 'https://example.com/math-notes.pdf',
    downloads: 45,
  },
  {
    id: '2',
    title: 'Physics Lab Manual',
    category: 'Physics',
    type: 'PDF',
    uploadedBy: 'Jane Smith',
    uploadedAt: '2024-01-14',
    url: 'https://example.com/physics-lab.pdf',
    downloads: 32,
  },
  {
    id: '3',
    title: 'Chemistry Tutorial Videos',
    category: 'Chemistry',
    type: 'Link',
    uploadedBy: 'Mike Johnson',
    uploadedAt: '2024-01-13',
    url: 'https://youtube.com/chemistry-tutorials',
    downloads: 78,
  },
];

export const mockReminders = [
  {
    id: '1',
    title: 'Mathematics Assignment Due',
    description: 'Complete calculus problems 1-20',
    dueDate: '2024-01-20',
    priority: 'high',
    category: 'assignment',
  },
  {
    id: '2',
    title: 'Physics Lab Report',
    description: 'Submit pendulum experiment report',
    dueDate: '2024-01-22',
    priority: 'medium',
    category: 'assignment',
  },
  {
    id: '3',
    title: 'Student Council Meeting',
    description: 'Monthly student council meeting',
    dueDate: '2024-01-25',
    priority: 'low',
    category: 'event',
  },
];

export const mockClubs = [
  {
    id: '1',
    name: 'Computer Science Society',
    description: 'A community for CS students to learn and collaborate',
    members: 156,
    category: 'Academic',
    meetingTime: 'Fridays 3:00 PM',
    contact: 'cs.society@university.edu',
    image: 'https://images.pexels.com/photos/574071/pexels-photo-574071.jpeg?auto=compress&cs=tinysrgb&w=400',
  },
  {
    id: '2',
    name: 'Drama Club',
    description: 'Express yourself through acting and theater',
    members: 89,
    category: 'Arts',
    meetingTime: 'Tuesdays 4:00 PM',
    contact: 'drama.club@university.edu',
    image: 'https://images.pexels.com/photos/3778056/pexels-photo-3778056.jpeg?auto=compress&cs=tinysrgb&w=400',
  },
  {
    id: '3',
    name: 'Environment Club',
    description: 'Promoting environmental awareness and sustainability',
    members: 124,
    category: 'Service',
    meetingTime: 'Wednesdays 2:00 PM',
    contact: 'environment@university.edu',
    image: 'https://images.pexels.com/photos/346885/pexels-photo-346885.jpeg?auto=compress&cs=tinysrgb&w=400',
  },
];

export const mockLostFound = [
  {
    id: '1',
    title: 'Lost: Blue Backpack',
    description: 'Blue Jansport backpack lost in library',
    category: 'lost',
    date: '2024-01-15',
    location: 'Main Library',
    contact: 'john.doe@student.edu',
    image: 'https://images.pexels.com/photos/2905238/pexels-photo-2905238.jpeg?auto=compress&cs=tinysrgb&w=400',
  },
  {
    id: '2',
    title: 'Found: Calculator',
    description: 'Scientific calculator found in Math building',
    category: 'found',
    date: '2024-01-14',
    location: 'Mathematics Building',
    contact: 'jane.smith@student.edu',
    image: 'https://images.pexels.com/photos/6238297/pexels-photo-6238297.jpeg?auto=compress&cs=tinysrgb&w=400',
  },
];

export const mockJobs = [
  {
    id: '1',
    title: 'Part-time Teaching Assistant',
    company: 'University Math Department',
    location: 'Campus',
    type: 'Part-time',
    salary: 'LKR 15,000/month',
    description: 'Assist professors with grading and tutoring students',
    requirements: 'Good grades in Mathematics courses',
    contact: 'math.dept@university.edu',
    postedDate: '2024-01-15',
  },
  {
    id: '2',
    title: 'Campus Tour Guide',
    company: 'Student Services',
    location: 'Campus',
    type: 'Part-time',
    salary: 'LKR 800/hour',
    description: 'Guide prospective students and visitors around campus',
    requirements: 'Good communication skills, friendly personality',
    contact: 'tours@university.edu',
    postedDate: '2024-01-14',
  },
  {
    id: '3',
    title: 'Research Assistant',
    company: 'Computer Science Department',
    location: 'CS Lab',
    type: 'Part-time',
    salary: 'LKR 20,000/month',
    description: 'Assist with ongoing research projects',
    requirements: 'CS major, programming skills',
    contact: 'research@cs.university.edu',
    postedDate: '2024-01-13',
  },
];

export const mockForumPosts = [
  {
    id: '1',
    title: 'Help with Calculus Assignment',
    content: 'Can someone explain how to solve integration by parts?',
    author: 'Student123',
    category: 'Academic',
    replies: 5,
    createdAt: '2024-01-15',
    likes: 8,
  },
  {
    id: '2',
    title: 'Study Group for Physics',
    content: 'Looking for students to form a study group for Physics 101',
    author: 'PhysicsLover',
    category: 'Study Groups',
    replies: 12,
    createdAt: '2024-01-14',
    likes: 15,
  },
  {
    id: '3',
    title: 'Dealing with Exam Stress',
    content: 'Any tips for managing stress during exam season?',
    author: 'AnxiousStudent',
    category: 'Personal',
    replies: 8,
    createdAt: '2024-01-13',
    likes: 20,
  },
];

export const mockGrades = [
  {
    subject: 'Mathematics',
    grade: 'A',
    credits: 4,
    gpa: 4.0,
    semester: 'Fall 2023',
  },
  {
    subject: 'Physics',
    grade: 'B+',
    credits: 3,
    gpa: 3.3,
    semester: 'Fall 2023',
  },
  {
    subject: 'Chemistry',
    grade: 'A-',
    credits: 3,
    gpa: 3.7,
    semester: 'Fall 2023',
  },
  {
    subject: 'English',
    grade: 'B',
    credits: 2,
    gpa: 3.0,
    semester: 'Fall 2023',
  },
];